DrMockTest: Throw error if test file doesn't exist
Without this error, a missing test file in a DrMockTest call would
result in the following very unfortunate linker error:

Undefined symbols for architecture x86_64:
  "_main", referenced from:
    implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64